# Schema Migration Pipeline
#
# This pipeline validates XML against source schema, transforms to target schema,
# validates the migrated document, generates a diff report, and archives the original.
#
# Usage:
#   xml-lib pipeline run templates/pipelines/schema-migration.yaml legacy-data.xml

name: schema_migration
description: Migrate XML documents from legacy schema to new schema version

error_strategy: rollback
rollback_enabled: true
max_snapshots: 100

variables:
  migration_id: "{{ datetime.now().isoformat() }}"
  source_version: "1.0"
  target_version: "2.0"

stages:
  # Stage 1: Validate source schema compliance
  - type: validate
    name: validate_source_schema
    schemas_dir: schemas/legacy/v1
    guardrails_dir: guardrails/legacy
    strict: true
    streaming: true  # Support large legacy files

  # Stage 2: Pre-migration data quality checks
  - type: validate
    name: data_quality_checks
    schemas_dir: schemas/legacy/v1
    guardrails_dir: guardrails/data-quality
    strict: false  # Warnings are OK, we'll fix during migration

  # Stage 3: Transform to target schema
  - type: transform
    name: migrate_to_v2
    transform: transforms/migrations/v1-to-v2.xsl
    params:
      migration_id: "${migration_id}"
      source_version: "${source_version}"
      target_version: "${target_version}"

  # Stage 4: Validate target schema compliance
  - type: validate
    name: validate_target_schema
    schemas_dir: schemas/v2
    guardrails_dir: guardrails/v2
    strict: true

  # Stage 5: Data integrity verification
  - type: validate
    name: verify_data_integrity
    schemas_dir: schemas/v2
    guardrails_dir: guardrails/integrity
    strict: true

  # Stage 6: Output migrated XML
  - type: output
    name: output_migrated_xml
    format: xml
    output_path: out/migrations/${migration_id}/migrated.xml

  # Stage 7: Generate migration diff report
  - type: output
    name: generate_diff_report
    format: html
    output_path: out/migrations/${migration_id}/diff-report.html
    template: templates/migration-diff.xsl

  # Stage 8: Generate assertions ledger for audit trail
  - type: output
    name: generate_audit_trail
    format: assertions
    output_path: out/migrations/${migration_id}/audit.jsonl
    options:
      include_signatures: true
      include_checksums: true
